config/routes.rb
Rails.application.routes.draw do
  resources :variants
  resources :variants
  resources :option_values
  resources :option_types
  resources :properties
  resources :products

  root 'products#index'

end

app/models/option_value.rb
# name:string presentation:string position:integer option_type:ref

class OptionValue < ActiveRecord::Base
  belongs_to :option_type, touch: true

  has_many :option_value_variants
  has_many :variants, through: :option_value_variants

  #validates :name, presence: true, uniqueness: { scope: :option_type_id }
  validates :presentation, presence: true

  after_touch :touch_all_variants

  private

  def touch_all_variants
    variants.update_all(updated_at: Time.current)
  end
end

app/controllers/option_values_controller.rb
class OptionValuesController < ApplicationController
  before_action :set_option_value, only: [:show, :edit, :update, :destroy]

  # GET /option_values
  # GET /option_values.json
  def index
    @option_values = OptionValue.all
  end

  # GET /option_values/1
  # GET /option_values/1.json
  def show
  end

  # GET /option_values/new
  def new
    @option_value = OptionValue.new
  end

  # GET /option_values/1/edit
  def edit
  end

  # POST /option_values
  # POST /option_values.json
  def create
    @option_value = OptionValue.new(option_value_params)

    respond_to do |format|
      if @option_value.save
        format.html { redirect_to @option_value, notice: 'Option value was successfully created.' }
        format.json { render :show, status: :created, location: @option_value }
      else
        format.html { render :new }
        format.json { render json: @option_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_values/1
  # PATCH/PUT /option_values/1.json
  def update
    respond_to do |format|
      if @option_value.update(option_value_params)
        format.html { redirect_to @option_value, notice: 'Option value was successfully updated.' }
        format.json { render :show, status: :ok, location: @option_value }
      else
        format.html { render :edit }
        format.json { render json: @option_value.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_values/1
  # DELETE /option_values/1.json
  def destroy
    @option_value.destroy
    respond_to do |format|
      format.html { redirect_to option_values_url, notice: 'Option value was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_value
      @option_value = OptionValue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_value_params
      params.require(:option_value).permit(:name, :presentation, :position, :option_type_id)
    end
end

app/helpers/option_values_helper.rb
module OptionValuesHelper
end

app/views/option_values/_form.html.erb
<%= form_for(@option_value) do |f| %>
  <% if @option_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option_value.errors.count, "error") %> prohibited this option_value from being saved:</h2>

      <ul>
      <% @option_value.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :presentation %><br>
    <%= f.text_field :presentation %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :option_type_id %><br>
    <%= f.text_field :option_type_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/option_values/edit.html.erb
<h1>Editing Option Value</h1>

<%= render 'form' %>

<%= link_to 'Show', @option_value %> |
<%= link_to 'Back', option_values_path %>

app/views/option_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Option Values</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Presentation</th>
      <th>Position</th>
      <th>Option type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @option_values.each do |option_value| %>
      <tr>
        <td><%= option_value.name %></td>
        <td><%= option_value.presentation %></td>
        <td><%= option_value.position %></td>
        <td><%= option_value.option_type %></td>
        <td><%= link_to 'Show', option_value %></td>
        <td><%= link_to 'Edit', edit_option_value_path(option_value) %></td>
        <td><%= link_to 'Destroy', option_value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option value', new_option_value_path %>

app/views/option_values/new.html.erb
<h1>New Option Value</h1>

<%= render 'form' %>

<%= link_to 'Back', option_values_path %>

app/views/option_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option_value.name %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @option_value.presentation %>
</p>

<p>
  <strong>Position:</strong>
  <%= @option_value.position %>
</p>

<p>
  <strong>Option type:</strong>
  <%= @option_value.option_type %>
</p>

<%= link_to 'Edit', edit_option_value_path(@option_value) %> |
<%= link_to 'Back', option_values_path %>