config/routes.rb
Rails.application.routes.draw do
  resources :variants
  resources :variants
  resources :option_values
  resources :option_types
  resources :properties
  resources :products

  root 'products#index'

end

app/controllers/option_types_controller.rb
class OptionTypesController < ApplicationController
  before_action :set_option_type, only: [:show, :edit, :update, :destroy]

  # GET /option_types
  # GET /option_types.json
  def index
    @option_types = OptionType.all
  end

  # GET /option_types/1
  # GET /option_types/1.json
  def show
  end

  # GET /option_types/new
  def new
    @option_type = OptionType.new
  end

  # GET /option_types/1/edit
  def edit
  end

  # POST /option_types
  # POST /option_types.json
  def create
    @option_type = OptionType.new(option_type_params)

    respond_to do |format|
      if @option_type.save
        format.html { redirect_to @option_type, notice: 'Option type was successfully created.' }
        format.json { render :show, status: :created, location: @option_type }
      else
        format.html { render :new }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /option_types/1
  # PATCH/PUT /option_types/1.json
  def update
    respond_to do |format|
      if @option_type.update(option_type_params)
        format.html { redirect_to @option_type, notice: 'Option type was successfully updated.' }
        format.json { render :show, status: :ok, location: @option_type }
      else
        format.html { render :edit }
        format.json { render json: @option_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /option_types/1
  # DELETE /option_types/1.json
  def destroy
    @option_type.destroy
    respond_to do |format|
      format.html { redirect_to option_types_url, notice: 'Option type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option_type
      @option_type = OptionType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_type_params
      params.require(:option_type).permit(:name, :presentation, :position)
    end
end

app/helpers/option_types_helper.rb
module OptionTypesHelper
end

app/views/option_types/_form.html.erb
<%= form_for(@option_type) do |f| %>
  <% if @option_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option_type.errors.count, "error") %> prohibited this option_type from being saved:</h2>

      <ul>
      <% @option_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :presentation %><br>
    <%= f.text_field :presentation %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/option_types/edit.html.erb
<h1>Editing Option Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @option_type %> |
<%= link_to 'Back', option_types_path %>

app/views/option_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Option Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Presentation</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @option_types.each do |option_type| %>
      <tr>
        <td><%= option_type.name %></td>
        <td><%= option_type.presentation %></td>
        <td><%= option_type.position %></td>
        <td><%= link_to 'Show', option_type %></td>
        <td><%= link_to 'Edit', edit_option_type_path(option_type) %></td>
        <td><%= link_to 'Destroy', option_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option type', new_option_type_path %>

app/views/option_types/new.html.erb
<h1>New Option Type</h1>

<%= render 'form' %>

<%= link_to 'Back', option_types_path %>

app/views/option_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @option_type.name %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @option_type.presentation %>
</p>

<p>
  <strong>Position:</strong>
  <%= @option_type.position %>
</p>

<%= link_to 'Edit', edit_option_type_path(@option_type) %> |
<%= link_to 'Back', option_types_path %>