config/routes.rb
Rails.application.routes.draw do
  resources :variants
  resources :variants
  resources :option_values
  resources :option_types
  resources :properties
  resources :products

  root 'products#index'

end

app/models/product.rb
# name:string description:string available_on:date available_until:date

class Product < ActiveRecord::Base

  has_many :product_option_types, dependent: :destroy, inverse_of: :product
  has_many :option_types, through: :product_option_types
  alias :options :product_option_types

  has_many :product_properties, dependent: :destroy, inverse_of: :product
  has_many :properties, through: :product_properties

  has_one :master,
          -> { where is_master: true },
          inverse_of: :product,
          class_name: 'Variant'

  has_many :variants,
           -> { where(is_master: false).order("#{::Variant.quoted_table_name}.position ASC") },
           inverse_of: :product,
           class_name: 'Variant'

  has_many :variants_including_master,
           -> { order("#{::Variant.quoted_table_name}.position ASC") },
           inverse_of: :product,
           class_name: 'Variant',
           dependent: :destroy

  after_initialize :ensure_master

  before_validation :validate_master

  def property(property_name)
    return nil unless prop = properties.find_by(name: property_name)
    product_properties.find_by(property: prop).try(:value)
  end

  def set_property(property_name, property_value, property_presentation = property_name)
    ActiveRecord::Base.transaction do
      # Works around spree_i18n #301
      property = if Property.exists?(name: property_name)
                   Property.where(name: property_name).first
                 else
                   Property.create(name: property_name, presentation: property_presentation)
                 end
      product_property = ProductProperty.where(product: self, property: property).first_or_initialize
      product_property.value = property_value
      product_property.save!
    end
  end


  def build_coffee_variants
    values = option_types.where(name: 'preparation').first.option_values.collect(&:name)
    puts values
    values.each do |ot|
      variant = variants.create(
        price: master.price
      )
      variant.set_option_value('preparation',ot)
    end
    save
  end

  private

  def ensure_master
    return unless new_record?
    self.master ||= build_master
  end

  # If the master cannot be saved, the Product object will get its errors
  # and will be destroyed
  def validate_master
    # We call master.default_price here to ensure price is initialized.
    # Required to avoid Variant#check_price validation failing on create.
    unless master.valid?
      master.errors.each do |att, error|
        self.errors.add(att, error)
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :available_on, :available_until)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :available_on %><br>
    <%= f.date_select :available_on %>
  </div>
  <div class="field">
    <%= f.label :available_until %><br>
    <%= f.date_select :available_until %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Available on</th>
      <th>Available until</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.available_on %></td>
        <td><%= product.available_until %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Available on:</strong>
  <%= @product.available_on %>
</p>

<p>
  <strong>Available until:</strong>
  <%= @product.available_until %>
</p>

<h3>Properties</h3>

<% @product.product_properties.each do |pp| %>
  <p>
    <%= link_to "#{pp.property.presentation} (#{pp.property.id}) = #{pp.value}", property_path(pp.property) %>
  </p>
<% end %>

<h3>Options</h3>

<% @product.option_types.each do |ot| %>
  <p>
    <%= link_to "#{ot.name} (#{ot.id})", option_type_path(ot) %>
  </p>
<% end %>

<h3>Variants</h3>

<% @product.variants_including_master.each do |v| %>
  <p>
    <%= link_to "#{v.sku} #{v.price} #{v.position} (#{v.id})", variant_path(v) %>
    <ul>
      <% @product.option_types.each do |ot| %>
        <li> <%= ot.name %> = <%= v.option_value(ot.name) %>
      <% end %>
      
    </ul>
  </p>
<% end %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>